<?php
    if(Zend_Auth::getInstance()->hasIdentity()){
        $usuario = Zend_Auth::getInstance()->getIdentity();
    }
?>
<header>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-10 col-md-offset-1">
                    <!-- Cabeçalho da barra -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/dashboard">Header</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
</header>