<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-md-offset-1">
        <ul class="menu-dashboard">
            <li><a href="/lancamento/novo">
                <span class="glyphicon glyphicon-plus ico ico-novo-lanc"></span>
                Novo Lançamento
            </a></li>
            <li><a href="/lancamento/transacao">
                <span class="glyphicon glyphicon-plus-sign ico ico-novo-dc"></span>
                Novo Crédito/Débito
            </a></li>
            <li><a href="/conta">
                <span class="glyphicon glyphicon-user ico ico-conta"></span>
                Conta
            </a></li>
            <li><a href="/lancamento">
                <span class="glyphicon glyphicon-usd ico ico-lanc"></span>
                Lançamentos
            </a></li>
            <li><a href="/produto">
                <span class="glyphicon glyphicon-list-alt ico ico-produto"></span>
                Produtos
            </a></li>
            <li><a href="/acesso/sair">
                <span class="glyphicon glyphicon-log-out ico ico-sair"></span>
                Sair
            </a></li>
        </ul>
    </div>
</div>